import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TranStackProvider from './components/providers/TanStackProvider'
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'harolDesigner.art',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TranStackProvider>
        {children}
        <Analytics />
        </TranStackProvider>
        </body>
    </html>
  )
}
